const mongoose = require("mongoose");
const { Schema } = mongoose;

const schema = new Schema({
    "Implant Brand": { type: String },
    "Implant Model": { type: String },
    "Implant Diameter": { type: Schema.Types.Mixed },
    "Implant Platform": { type: Schema.Types.Mixed },
    "Implant Length": { type: String },
    "Drill Kit Type": { type: String },
    "Drill Sequence Option": { type: String },
    "Drill Kit Name": { type: String },
    "Drill Kit Item Number": { type: String },
    "Drill Kit Link to Purchase": { type: String },
    "Drill 1 (Extra Short) Name": { type: String},
    "Drill 1 (Extra Short) Item Number": { type: String},
    "Drill 1 (Extra Short) Link to Purchase": { type: String },
    "Drill 1 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 1 (Short) Name": { type: String},
    "Drill 1 (Short) Item Number": { type: String},
    "Drill 1 (Short) Link to Purchase": { type: String },
    "Drill 1 (Short) Manufacturer Recommendations": { type: String },
    "Drill 1 (Short) Name": { type: String},
    "Drill 1 (Short) Item Number": { type: String},
    "Drill 1 (Short) Link to Purchase": { type: String },
    "Drill 1 (Short) Manufacturer Recommendations": { type: String },
    "Drill 1 (Standard / Medium) Name": { type: String},
    "Drill 1 (Standard / Medium) Item Number": { type: String},
    "Drill 1 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 1 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 1 (Long) Name": { type: String},
    "Drill 1 (Long) Item Number": { type: String},
    "Drill 1 (Long) Link to Purchase": { type: String },
    "Drill 1 (Long) Manufacturer Recommendations": { type: String },
    "Drill 2 (Extra Short) Name": { type: String},
    "Drill 2 (Extra Short) Item Number": { type: String},
    "Drill 2 (Extra Short) Link to Purchase": { type: String },
    "Drill 2 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 2 (Short) Name": { type: String},
    "Drill 2 (Short) Item Number": { type: String},
    "Drill 2 (Short) Link to Purchase": { type: String },
    "Drill 2 (Short) Manufacturer Recommendations": { type: String },
    "Drill 2 (Short) Name": { type: String},
    "Drill 2 (Short) Item Number": { type: String},
    "Drill 2 (Short) Link to Purchase": { type: String },
    "Drill 2 (Short) Manufacturer Recommendations": { type: String },
    "Drill 2 (Standard / Medium) Name": { type: String},
    "Drill 2 (Standard / Medium) Item Number": { type: String},
    "Drill 2 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 2 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 2 (Long) Name": { type: String},
    "Drill 2 (Long) Item Number": { type: String},
    "Drill 2 (Long) Link to Purchase": { type: String },
    "Drill 2 (Long) Manufacturer Recommendations": { type: String },
    "Drill 3 (Extra Short) Name": { type: String},
    "Drill 3 (Extra Short) Item Number": { type: String},
    "Drill 3 (Extra Short) Link to Purchase": { type: String },
    "Drill 3 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 3 (Short) Name": { type: String},
    "Drill 3 (Short) Item Number": { type: String},
    "Drill 3 (Short) Link to Purchase": { type: String },
    "Drill 3 (Short) Manufacturer Recommendations": { type: String },
    "Drill 3 (Short) Name": { type: String},
    "Drill 3 (Short) Item Number": { type: String},
    "Drill 3 (Short) Link to Purchase": { type: String },
    "Drill 3 (Short) Manufacturer Recommendations": { type: String },
    "Drill 3 (Standard / Medium) Name": { type: String},
    "Drill 3 (Standard / Medium) Item Number": { type: String},
    "Drill 3 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 3 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 3 (Long) Name": { type: String},
    "Drill 3 (Long) Item Number": { type: String},
    "Drill 3 (Long) Link to Purchase": { type: String },
    "Drill 3 (Long) Manufacturer Recommendations": { type: String },
    "Drill 4 (Extra Short) Name": { type: String},
    "Drill 4 (Extra Short) Item Number": { type: String},
    "Drill 4 (Extra Short) Link to Purchase": { type: String },
    "Drill 4 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 4 (Short) Name": { type: String},
    "Drill 4 (Short) Item Number": { type: String},
    "Drill 4 (Short) Link to Purchase": { type: String },
    "Drill 4 (Short) Manufacturer Recommendations": { type: String },
    "Drill 4 (Short) Name": { type: String},
    "Drill 4 (Short) Item Number": { type: String},
    "Drill 4 (Short) Link to Purchase": { type: String },
    "Drill 4 (Short) Manufacturer Recommendations": { type: String },
    "Drill 4 (Standard / Medium) Name": { type: String},
    "Drill 4 (Standard / Medium) Item Number": { type: String},
    "Drill 4 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 4 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 4 (Long) Name": { type: String},
    "Drill 4 (Long) Item Number": { type: String},
    "Drill 4 (Long) Link to Purchase": { type: String },
    "Drill 4 (Long) Manufacturer Recommendations": { type: String },
    "Drill 5 (Extra Short) Name": { type: String},
    "Drill 5 (Extra Short) Item Number": { type: String},
    "Drill 5 (Extra Short) Link to Purchase": { type: String },
    "Drill 5 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 5 (Short) Name": { type: String},
    "Drill 5 (Short) Item Number": { type: String},
    "Drill 5 (Short) Link to Purchase": { type: String },
    "Drill 5 (Short) Manufacturer Recommendations": { type: String },
    "Drill 5 (Short) Name": { type: String},
    "Drill 5 (Short) Item Number": { type: String},
    "Drill 5 (Short) Link to Purchase": { type: String },
    "Drill 5 (Short) Manufacturer Recommendations": { type: String },
    "Drill 5 (Standard / Medium) Name": { type: String},
    "Drill 5 (Standard / Medium) Item Number": { type: String},
    "Drill 5 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 5 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 5 (Long) Name": { type: String},
    "Drill 5 (Long) Item Number": { type: String},
    "Drill 5 (Long) Link to Purchase": { type: String },
    "Drill 5 (Long) Manufacturer Recommendations": { type: String },
    "Drill 6 (Extra Short) Name": { type: String},
    "Drill 6 (Extra Short) Item Number": { type: String},
    "Drill 6 (Extra Short) Link to Purchase": { type: String },
    "Drill 6 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 6 (Short) Name": { type: String},
    "Drill 6 (Short) Item Number": { type: String},
    "Drill 6 (Short) Link to Purchase": { type: String },
    "Drill 6 (Short) Manufacturer Recommendations": { type: String },
    "Drill 6 (Short) Name": { type: String},
    "Drill 6 (Short) Item Number": { type: String},
    "Drill 6 (Short) Link to Purchase": { type: String },
    "Drill 6 (Short) Manufacturer Recommendations": { type: String },
    "Drill 6 (Standard / Medium) Name": { type: String},
    "Drill 6 (Standard / Medium) Item Number": { type: String},
    "Drill 6 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 6 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 6 (Long) Name": { type: String},
    "Drill 6 (Long) Item Number": { type: String},
    "Drill 6 (Long) Link to Purchase": { type: String },
    "Drill 6 (Long) Manufacturer Recommendations": { type: String },
    "Drill 7 (Extra Short) Name": { type: String},
    "Drill 7 (Extra Short) Item Number": { type: String},
    "Drill 7 (Extra Short) Link to Purchase": { type: String },
    "Drill 7 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 7 (Short) Name": { type: String},
    "Drill 7 (Short) Item Number": { type: String},
    "Drill 7 (Short) Link to Purchase": { type: String },
    "Drill 7 (Short) Manufacturer Recommendations": { type: String },
    "Drill 7 (Short) Name": { type: String},
    "Drill 7 (Short) Item Number": { type: String},
    "Drill 7 (Short) Link to Purchase": { type: String },
    "Drill 7 (Short) Manufacturer Recommendations": { type: String },
    "Drill 7 (Standard / Medium) Name": { type: String},
    "Drill 7 (Standard / Medium) Item Number": { type: String},
    "Drill 7 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 7 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 7 (Long) Name": { type: String},
    "Drill 7 (Long) Item Number": { type: String},
    "Drill 7 (Long) Link to Purchase": { type: String },
    "Drill 7 (Long) Manufacturer Recommendations": { type: String },
    "Drill 8 (Extra Short) Name": { type: String},
    "Drill 8 (Extra Short) Item Number": { type: String},
    "Drill 8 (Extra Short) Link to Purchase": { type: String },
    "Drill 8 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 8 (Short) Name": { type: String},
    "Drill 8 (Short) Item Number": { type: String},
    "Drill 8 (Short) Link to Purchase": { type: String },
    "Drill 8 (Short) Manufacturer Recommendations": { type: String },
    "Drill 8 (Short) Name": { type: String},
    "Drill 8 (Short) Item Number": { type: String},
    "Drill 8 (Short) Link to Purchase": { type: String },
    "Drill 8 (Short) Manufacturer Recommendations": { type: String },
    "Drill 8 (Standard / Medium) Name": { type: String},
    "Drill 8 (Standard / Medium) Item Number": { type: String},
    "Drill 8 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 8 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 8 (Long) Name": { type: String},
    "Drill 8 (Long) Item Number": { type: String},
    "Drill 8 (Long) Link to Purchase": { type: String },
    "Drill 8 (Long) Manufacturer Recommendations": { type: String },
    "Drill 9 (Extra Short) Name": { type: String},
    "Drill 9 (Extra Short) Item Number": { type: String},
    "Drill 9 (Extra Short) Link to Purchase": { type: String },
    "Drill 9 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 9 (Short) Name": { type: String},
    "Drill 9 (Short) Item Number": { type: String},
    "Drill 9 (Short) Link to Purchase": { type: String },
    "Drill 9 (Short) Manufacturer Recommendations": { type: String },
    "Drill 9 (Short) Name": { type: String},
    "Drill 9 (Short) Item Number": { type: String},
    "Drill 9 (Short) Link to Purchase": { type: String },
    "Drill 9 (Short) Manufacturer Recommendations": { type: String },
    "Drill 9 (Standard / Medium) Name": { type: String},
    "Drill 9 (Standard / Medium) Item Number": { type: String},
    "Drill 9 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 9 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 9 (Long) Name": { type: String},
    "Drill 9 (Long) Item Number": { type: String},
    "Drill 9 (Long) Link to Purchase": { type: String },
    "Drill 9 (Long) Manufacturer Recommendations": { type: String },
    "Drill 10 (Extra Short) Name": { type: String},
    "Drill 10 (Extra Short) Item Number": { type: String},
    "Drill 10 (Extra Short) Link to Purchase": { type: String },
    "Drill 10 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 10 (Short) Name": { type: String},
    "Drill 10 (Short) Item Number": { type: String},
    "Drill 10 (Short) Link to Purchase": { type: String },
    "Drill 10 (Short) Manufacturer Recommendations": { type: String },
    "Drill 10 (Short) Name": { type: String},
    "Drill 10 (Short) Item Number": { type: String},
    "Drill 10 (Short) Link to Purchase": { type: String },
    "Drill 10 (Short) Manufacturer Recommendations": { type: String },
    "Drill 10 (Standard / Medium) Name": { type: String},
    "Drill 10 (Standard / Medium) Item Number": { type: String},
    "Drill 10 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 10 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 10 (Long) Name": { type: String},
    "Drill 10 (Long) Item Number": { type: String},
    "Drill 10 (Long) Link to Purchase": { type: String },
    "Drill 10 (Long) Manufacturer Recommendations": { type: String },
    "Drill 11 (Extra Short) Name": { type: String},
    "Drill 11 (Extra Short) Item Number": { type: String},
    "Drill 11 (Extra Short) Link to Purchase": { type: String },
    "Drill 11 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 11 (Short) Name": { type: String},
    "Drill 11 (Short) Item Number": { type: String},
    "Drill 11 (Short) Link to Purchase": { type: String },
    "Drill 11 (Short) Manufacturer Recommendations": { type: String },
    "Drill 11 (Short) Name": { type: String},
    "Drill 11 (Short) Item Number": { type: String},
    "Drill 11 (Short) Link to Purchase": { type: String },
    "Drill 11 (Short) Manufacturer Recommendations": { type: String },
    "Drill 11 (Standard / Medium) Name": { type: String},
    "Drill 11 (Standard / Medium) Item Number": { type: String},
    "Drill 11 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 11 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 11 (Long) Name": { type: String},
    "Drill 11 (Long) Item Number": { type: String},
    "Drill 11 (Long) Link to Purchase": { type: String },
    "Drill 11 (Long) Manufacturer Recommendations": { type: String },
    "Drill 12 (Extra Short) Name": { type: String},
    "Drill 12 (Extra Short) Item Number": { type: String},
    "Drill 12 (Extra Short) Link to Purchase": { type: String },
    "Drill 12 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 12 (Short) Name": { type: String},
    "Drill 12 (Short) Item Number": { type: String},
    "Drill 12 (Short) Link to Purchase": { type: String },
    "Drill 12 (Short) Manufacturer Recommendations": { type: String },
    "Drill 12 (Short) Name": { type: String},
    "Drill 12 (Short) Item Number": { type: String},
    "Drill 12 (Short) Link to Purchase": { type: String },
    "Drill 12 (Short) Manufacturer Recommendations": { type: String },
    "Drill 12 (Standard / Medium) Name": { type: String},
    "Drill 12 (Standard / Medium) Item Number": { type: String},
    "Drill 12 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 12 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 12 (Long) Name": { type: String},
    "Drill 12 (Long) Item Number": { type: String},
    "Drill 12 (Long) Link to Purchase": { type: String },
    "Drill 12 (Long) Manufacturer Recommendations": { type: String },
    "Drill 13 (Extra Short) Name": { type: String},
    "Drill 13 (Extra Short) Item Number": { type: String},
    "Drill 13 (Extra Short) Link to Purchase": { type: String },
    "Drill 13 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 13 (Short) Name": { type: String},
    "Drill 13 (Short) Item Number": { type: String},
    "Drill 13 (Short) Link to Purchase": { type: String },
    "Drill 13 (Short) Manufacturer Recommendations": { type: String },
    "Drill 13 (Short) Name": { type: String},
    "Drill 13 (Short) Item Number": { type: String},
    "Drill 13 (Short) Link to Purchase": { type: String },
    "Drill 13 (Short) Manufacturer Recommendations": { type: String },
    "Drill 13 (Standard / Medium) Name": { type: String},
    "Drill 13 (Standard / Medium) Item Number": { type: String},
    "Drill 13 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 13 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 13 (Long) Name": { type: String},
    "Drill 13 (Long) Item Number": { type: String},
    "Drill 13 (Long) Link to Purchase": { type: String },
    "Drill 13 (Long) Manufacturer Recommendations": { type: String },
    "Drill 14 (Extra Short) Name": { type: String},
    "Drill 14 (Extra Short) Item Number": { type: String},
    "Drill 14 (Extra Short) Link to Purchase": { type: String },
    "Drill 14 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 14 (Short) Name": { type: String},
    "Drill 14 (Short) Item Number": { type: String},
    "Drill 14 (Short) Link to Purchase": { type: String },
    "Drill 14 (Short) Manufacturer Recommendations": { type: String },
    "Drill 14 (Short) Name": { type: String},
    "Drill 14 (Short) Item Number": { type: String},
    "Drill 14 (Short) Link to Purchase": { type: String },
    "Drill 14 (Short) Manufacturer Recommendations": { type: String },
    "Drill 14 (Standard / Medium) Name": { type: String},
    "Drill 14 (Standard / Medium) Item Number": { type: String},
    "Drill 14 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 14 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 14 (Long) Name": { type: String},
    "Drill 14 (Long) Item Number": { type: String},
    "Drill 14 (Long) Link to Purchase": { type: String },
    "Drill 14 (Long) Manufacturer Recommendations": { type: String },
    "Drill 15 (Extra Short) Name": { type: String},
    "Drill 15 (Extra Short) Item Number": { type: String},
    "Drill 15 (Extra Short) Link to Purchase": { type: String },
    "Drill 15 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 15 (Short) Name": { type: String},
    "Drill 15 (Short) Item Number": { type: String},
    "Drill 15 (Short) Link to Purchase": { type: String },
    "Drill 15 (Short) Manufacturer Recommendations": { type: String },
    "Drill 15 (Short) Name": { type: String},
    "Drill 15 (Short) Item Number": { type: String},
    "Drill 15 (Short) Link to Purchase": { type: String },
    "Drill 15 (Short) Manufacturer Recommendations": { type: String },
    "Drill 15 (Standard / Medium) Name": { type: String},
    "Drill 15 (Standard / Medium) Item Number": { type: String},
    "Drill 15 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 15 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 15 (Long) Name": { type: String},
    "Drill 15 (Long) Item Number": { type: String},
    "Drill 15 (Long) Link to Purchase": { type: String },
    "Drill 15 (Long) Manufacturer Recommendations": { type: String },
    "Drill 16 (Extra Short) Name": { type: String},
    "Drill 16 (Extra Short) Item Number": { type: String},
    "Drill 16 (Extra Short) Link to Purchase": { type: String },
    "Drill 16 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 16 (Short) Name": { type: String},
    "Drill 16 (Short) Item Number": { type: String},
    "Drill 16 (Short) Link to Purchase": { type: String },
    "Drill 16 (Short) Manufacturer Recommendations": { type: String },
    "Drill 16 (Short) Name": { type: String},
    "Drill 16 (Short) Item Number": { type: String},
    "Drill 16 (Short) Link to Purchase": { type: String },
    "Drill 16 (Short) Manufacturer Recommendations": { type: String },
    "Drill 16 (Standard / Medium) Name": { type: String},
    "Drill 16 (Standard / Medium) Item Number": { type: String},
    "Drill 16 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 16 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 16 (Long) Name": { type: String},
    "Drill 16 (Long) Item Number": { type: String},
    "Drill 16 (Long) Link to Purchase": { type: String },
    "Drill 16 (Long) Manufacturer Recommendations": { type: String },
    "Drill 17 (Extra Short) Name": { type: String},
    "Drill 17 (Extra Short) Item Number": { type: String},
    "Drill 17 (Extra Short) Link to Purchase": { type: String },
    "Drill 17 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 17 (Short) Name": { type: String},
    "Drill 17 (Short) Item Number": { type: String},
    "Drill 17 (Short) Link to Purchase": { type: String },
    "Drill 17 (Short) Manufacturer Recommendations": { type: String },
    "Drill 17 (Short) Name": { type: String},
    "Drill 17 (Short) Item Number": { type: String},
    "Drill 17 (Short) Link to Purchase": { type: String },
    "Drill 17 (Short) Manufacturer Recommendations": { type: String },
    "Drill 17 (Standard / Medium) Name": { type: String},
    "Drill 17 (Standard / Medium) Item Number": { type: String},
    "Drill 17 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 17 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 17 (Long) Name": { type: String},
    "Drill 17 (Long) Item Number": { type: String},
    "Drill 17 (Long) Link to Purchase": { type: String },
    "Drill 17 (Long) Manufacturer Recommendations": { type: String },
    "Drill 18 (Extra Short) Name": { type: String},
    "Drill 18 (Extra Short) Item Number": { type: String},
    "Drill 18 (Extra Short) Link to Purchase": { type: String },
    "Drill 18 (Extra Short) Manufacturer Recommendations": { type: String },
    "Drill 18 (Short) Name": { type: String},
    "Drill 18 (Short) Item Number": { type: String},
    "Drill 18 (Short) Link to Purchase": { type: String },
    "Drill 18 (Short) Manufacturer Recommendations": { type: String },
    "Drill 18 (Short) Name": { type: String},
    "Drill 18 (Short) Item Number": { type: String},
    "Drill 18 (Short) Link to Purchase": { type: String },
    "Drill 18 (Short) Manufacturer Recommendations": { type: String },
    "Drill 18 (Standard / Medium) Name": { type: String},
    "Drill 18 (Standard / Medium) Item Number": { type: String},
    "Drill 18 (Standard / Medium) Link to Purchase": { type: String },
    "Drill 18 (Standard / Medium) Manufacturer Recommendations": { type: String },
    "Drill 18 (Long) Name": { type: String},
    "Drill 18 (Long) Item Number": { type: String},
    "Drill 18 (Long) Link to Purchase": { type: String },
    "Drill 18 (Long) Manufacturer Recommendations": { type: String },
})
const DrillKitAndSequenceModel = mongoose.model("DrillKitAndSequence", schema, "Surgery_DrillKitAndSequence");

module.exports = DrillKitAndSequenceModel;
